### ISSUE TITLE
Unable to use the attributes from the gRPC Response

### ISSUE THREAD

**Issue by abhaybhargav** [authzed/authzed-py#121] opened 2024-01-27 10:56 UTC
Hi there, I am trying to use this with the spicedb serverless product. 

I am able to create policies, etc. but when I try to run a CheckPermissionsRequest (which I know works), it doesnt allow me to access the `permissionship` attribute, as indicated in your examples. What am I possibly doing wrong?

```
resp = client.CheckPermission(
    CheckPermissionRequest(
        resource=company_ref,
        permission="administrator",
        subject=blah,
    ),
)

print(resp.permissionship)
```

**Comment by jtfidje** [comment] 2024-02-29 12:39
Hitting the same issue:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[36], line 1
----> 1 resp.permissionship

AttributeError: 'UnaryUnaryCall' object has no attribute 'permissionship'
```

**Comment by jtfidje** [comment] 2024-02-29 13:53
I used `poetry.lock` from your repo and now it seems fine. I _think_ maybe this error has something to do with an upgrade of the python grpc lib?

**Comment by tstirrat15** [comment] 2024-09-19 17:41
Given that there hasn't been any chatter on this, I'm going to assume the issue isn't present anymore and close the issue. Please let me know if you're still seeing this and we can reopen and debug.

**Closed by tstirrat15** 2024-09-19 17:41 UTC
